In [1]:
#Importing of libraries
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder, StandardScaler
import warnings
warnings.filterwarnings('ignore')

In [2]:
#reading the csv file
df=pd.read_csv("../Resources/Impact_of_Remote_Work_on_mental_Health.csv")

In [3]:
df["Stress_Level_New"] = df["Stress_Level"].replace({"Low": 0, "Medium": 0, "High": 1})

In [4]:
df["Stress_Level_New"].value_counts()

Stress_Level_New
0    3314
1    1686
Name: count, dtype: int64

In [5]:
df.head()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,...,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region,Stress_Level_New
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,...,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe,0
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,...,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia,0
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,...,Anxiety,No,No Change,4,Unsatisfied,5,NaN,Poor,North America,0
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,...,Depression,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe,1
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,...,NaN,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America,1

In [6]:
df.tail()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,...,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region,Stress_Level_New
4995,EMP4996,32,Male,Sales,Consulting,4,Onsite,24,2,5,...,Burnout,Yes,Decrease,4,Neutral,1,Weekly,Average,Asia,1
4996,EMP4997,39,Female,Sales,Healthcare,27,Onsite,48,15,1,...,Depression,Yes,Decrease,1,Satisfied,1,NaN,Average,Africa,0
4997,EMP4998,42,Female,Sales,Healthcare,21,Hybrid,34,1,4,...,Burnout,No,Increase,3,Satisfied,1,Daily,Poor,Oceania,1
4998,EMP4999,27,Female,Sales,Healthcare,26,Remote,58,0,5,...,NaN,Yes,Increase,3,Unsatisfied,4,Daily,Average,Asia,0
4999,EMP5000,29,Male,HR,IT,30,Onsite,20,15,1,...,Depression,Yes,No Change,3,Unsatisfied,5,NaN,Poor,Asia,0

In [7]:
df.shape

(5000, 21)

In [8]:
df.describe()

,Age,Years_of_Experience,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Social_Isolation_Rating,Company_Support_for_Remote_Work,Stress_Level_New
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,40.995000,17.810200,39.614600,7.559000,2.984200,2.993800,3.007800,0.337200
std,11.296021,10.020412,11.860194,4.636121,1.410513,1.394615,1.399046,0.472801
min,22.000000,1.000000,20.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,31.000000,9.000000,29.000000,4.000000,2.000000,2.000000,2.000000,0.000000
50%,41.000000,18.000000,40.000000,8.000000,3.000000,3.000000,3.000000,0.000000
75%,51.000000,26.000000,50.000000,12.000000,4.000000,4.000000,4.000000,1.000000
max,60.000000,35.000000,60.000000,15.000000,5.000000,5.000000,5.000000,1.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Employee_ID                        5000 non-null   object
 1   Age                                5000 non-null   int64
 2   Gender                             5000 non-null   object
 3   Job_Role                           5000 non-null   object
 4   Industry                           5000 non-null   object
 5   Years_of_Experience                5000 non-null   int64
 6   Work_Location                      5000 non-null   object
 7   Hours_Worked_Per_Week              5000 non-null   int64
 8   Number_of_Virtual_Meetings         5000 non-null   int64
 9   Work_Life_Balance_Rating           5000 non-null   int64
 10  Stress_Level                       5000 non-null   object
 11  Mental_Health_Condition            3804 non-null   object
 12  Access_to_Mental_Health_Resources  5000 non-null   object
 13  Productivity_Change                5000 non-null   object
 14  Social_Isolation_Rating            5000 non-null   int64
 15  Satisfaction_with_Remote_Work      5000 non-null   object
 16  Company_Support_for_Remote_Work    5000 non-null   int64
 17  Physical_Activity                  3371 non-null   object
 18  Sleep_Quality                      5000 non-null   object
 19  Region                             5000 non-null   object
 20  Stress_Level_New                   5000 non-null   int64
dtypes: int64(8), object(13)
memory usage: 820.4+ KB

In [10]:
df.isnull().sum()

Employee_ID                             0
Age                                     0
Gender                                  0
Job_Role                                0
Industry                                0
Years_of_Experience                     0
Work_Location                           0
Hours_Worked_Per_Week                   0
Number_of_Virtual_Meetings              0
Work_Life_Balance_Rating                0
Stress_Level                            0
Mental_Health_Condition              1196
Access_to_Mental_Health_Resources       0
Productivity_Change                     0
Social_Isolation_Rating                 0
Satisfaction_with_Remote_Work           0
Company_Support_for_Remote_Work         0
Physical_Activity                    1629
Sleep_Quality                           0
Region                                  0
Stress_Level_New                        0
dtype: int64

In [11]:
mode_value = df['Mental_Health_Condition'].mode()
if not mode_value.empty:
    mode_value = mode_value[0]  # Extract the first mode value
else:
    mode_value = "Unknown"  # Fallback in case the column is empty

In [12]:
# Replace missing values with the mode
mode_value = df['Mental_Health_Condition'].mode()[0]  # Get the most frequent value
df['Mental_Health_Condition'] = df['Mental_Health_Condition'].fillna(mode_value)

print(df['Mental_Health_Condition'].head())

0    Depression
1       Anxiety
2       Anxiety
3    Depression
4       Burnout
Name: Mental_Health_Condition, dtype: object

In [13]:
# Reset the index to avoid slicing issues
df.reset_index(drop=True, inplace=True)
df.head()

,Employee_ID,Age,Gender,Job_Role,Industry,Years_of_Experience,Work_Location,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,...,Mental_Health_Condition,Access_to_Mental_Health_Resources,Productivity_Change,Social_Isolation_Rating,Satisfaction_with_Remote_Work,Company_Support_for_Remote_Work,Physical_Activity,Sleep_Quality,Region,Stress_Level_New
0,EMP0001,32,Non-binary,HR,Healthcare,13,Hybrid,47,7,2,...,Depression,No,Decrease,1,Unsatisfied,1,Weekly,Good,Europe,0
1,EMP0002,40,Female,Data Scientist,IT,3,Remote,52,4,1,...,Anxiety,No,Increase,3,Satisfied,2,Weekly,Good,Asia,0
2,EMP0003,59,Non-binary,Software Engineer,Education,22,Hybrid,46,11,5,...,Anxiety,No,No Change,4,Unsatisfied,5,NaN,Poor,North America,0
3,EMP0004,27,Male,Software Engineer,Finance,20,Onsite,32,8,4,...,Depression,Yes,Increase,3,Unsatisfied,3,NaN,Poor,Europe,1
4,EMP0005,49,Male,Sales,Consulting,32,Onsite,35,12,2,...,Burnout,Yes,Decrease,3,Unsatisfied,3,Weekly,Average,North America,1

In [14]:
# Save the DataFrame to a CSV file
df.to_csv("updated_dataset.csv", index=False)

# Inform the user where the file is saved
print("The updated dataset has been saved as 'updated_dataset.csv' in the current directory.")

The updated dataset has been saved as 'updated_dataset.csv' in the current directory.

In [15]:
new_dataset = df.copy()

In [16]:
# Replace missing values with the mode
mode_value = df['Physical_Activity'].mode()[0]  # Get the most frequent value
df['Physical_Activity'] = df['Physical_Activity'].fillna(mode_value)

print(df['Physical_Activity'].head())

0    Weekly
1    Weekly
2    Weekly
3    Weekly
4    Weekly
Name: Physical_Activity, dtype: object

In [17]:
# Save the DataFrame to a CSV file
df.to_csv("updated_dataset.csv", index=False)

# Inform the user where the file is saved
print("The updated dataset has been saved as 'updated_dataset.csv' in the current directory.")

The updated dataset has been saved as 'updated_dataset.csv' in the current directory.

In [18]:
#seeing if the null value of Physical_Activity
df.isnull().sum()

Employee_ID                          0
Age                                  0
Gender                               0
Job_Role                             0
Industry                             0
Years_of_Experience                  0
Work_Location                        0
Hours_Worked_Per_Week                0
Number_of_Virtual_Meetings           0
Work_Life_Balance_Rating             0
Stress_Level                         0
Mental_Health_Condition              0
Access_to_Mental_Health_Resources    0
Productivity_Change                  0
Social_Isolation_Rating              0
Satisfaction_with_Remote_Work        0
Company_Support_for_Remote_Work      0
Physical_Activity                    0
Sleep_Quality                        0
Region                               0
Stress_Level_New                     0
dtype: int64

In [19]:
df.describe()

,Age,Years_of_Experience,Hours_Worked_Per_Week,Number_of_Virtual_Meetings,Work_Life_Balance_Rating,Social_Isolation_Rating,Company_Support_for_Remote_Work,Stress_Level_New
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,40.995000,17.810200,39.614600,7.559000,2.984200,2.993800,3.007800,0.337200
std,11.296021,10.020412,11.860194,4.636121,1.410513,1.394615,1.399046,0.472801
min,22.000000,1.000000,20.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,31.000000,9.000000,29.000000,4.000000,2.000000,2.000000,2.000000,0.000000
50%,41.000000,18.000000,40.000000,8.000000,3.000000,3.000000,3.000000,0.000000
75%,51.000000,26.000000,50.000000,12.000000,4.000000,4.000000,4.000000,1.000000
max,60.000000,35.000000,60.000000,15.000000,5.000000,5.000000,5.000000,1.000000

In [20]:
df["Mental_Health_Condition"].unique

<bound method Series.unique of 0       Depression
1          Anxiety
2          Anxiety
3       Depression
4          Burnout
           ...
4995       Burnout
4996    Depression
4997       Burnout
4998       Burnout
4999    Depression
Name: Mental_Health_Condition, Length: 5000, dtype: object>

In [21]:
df["Stress_Level_New"].value_counts()

Stress_Level_New
0    3314
1    1686
Name: count, dtype: int64

In [22]:
X = df.drop(columns=["Employee_ID", "Stress_Level","Stress_Level_New"])
y  = df["Stress_Level_New"]

In [23]:
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [24]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
X_encoded = pd.DataFrame(encoder.fit_transform(X[categorical_features]))
X_encoded.columns = encoder.get_feature_names_out(categorical_features)
X_encoded.index = X.index
X = X.drop(columns=categorical_features)
X = pd.concat([X, X_encoded], axis=1)

In [25]:
scaler = StandardScaler()
X[numerical_features] = scaler.fit_transform(X[numerical_features])

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
X_encoded

,Gender_Female,Gender_Male,Gender_Non-binary,Gender_Prefer not to say,Job_Role_Data Scientist,Job_Role_Designer,Job_Role_HR,Job_Role_Marketing,Job_Role_Project Manager,Job_Role_Sales,...,Physical_Activity_Weekly,Sleep_Quality_Average,Sleep_Quality_Good,Sleep_Quality_Poor,Region_Africa,Region_Asia,Region_Europe,Region_North America,Region_Oceania,Region_South America
0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4996,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4997,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4998,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4999,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0

In [28]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [29]:
y_pred = model.predict(X_test)

In [30]:
accuracy_score(y_test, y_pred)

0.66